-- ============================================================================
-- MIGRATION 03: All Tables (in dependency order)
-- ============================================================================

-- 1. countries (no dependencies)
CREATE TABLE public.countries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL UNIQUE,
    name_ar VARCHAR NOT NULL,
    name_en VARCHAR NOT NULL,
    currency_code VARCHAR NOT NULL CHECK (LENGTH(currency_code) = 3),
    currency_symbol VARCHAR NOT NULL,
    currency_name_ar VARCHAR NOT NULL,
    currency_name_en VARCHAR NOT NULL,
    country_code VARCHAR,
    phone_code VARCHAR,
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. pricing_plans (depends on countries)
CREATE TABLE public.pricing_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    country_id UUID REFERENCES public.countries(id) ON DELETE CASCADE,
    sessions_per_week INTEGER NOT NULL CHECK (sessions_per_week >= 1 AND sessions_per_week <= 20),
    monthly_price NUMERIC CHECK (monthly_price >= 0),
    plan_name VARCHAR,
    plan_name_ar VARCHAR,
    plan_name_en VARCHAR,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    is_default BOOLEAN DEFAULT false,
    discount_percentage NUMERIC DEFAULT 0 CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
    session_duration INTEGER DEFAULT 60 CHECK (session_duration > 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. teachers (no dependencies)
CREATE TABLE public.teachers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL,
    name_ar VARCHAR,
    name_en VARCHAR,
    phone VARCHAR,
    phone_secondary VARCHAR,
    email VARCHAR UNIQUE,
    gender VARCHAR CHECK (gender IN ('male', 'female')),
    date_of_birth DATE,
    nationality VARCHAR,
    address TEXT,
    hire_date DATE DEFAULT CURRENT_DATE,
    termination_date DATE,
    employment_type VARCHAR CHECK (employment_type IN ('full_time', 'part_time', 'contract', 'volunteer')),
    qualifications TEXT,
    certifications TEXT,
    specialization TEXT,
    experience_years INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended', 'on_leave', 'terminated')),
    salary_amount NUMERIC,
    salary_currency VARCHAR,
    payment_method VARCHAR,
    bank_account VARCHAR,
    overall_rating NUMERIC CHECK (overall_rating >= 0 AND overall_rating <= 5),
    total_ratings INTEGER DEFAULT 0,
    notes TEXT,
    profile_image_url TEXT,
    session_rate NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. students (depends on countries, pricing_plans, teachers)
CREATE TABLE public.students (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL,
    name_ar VARCHAR,
    name_en VARCHAR,
    phone VARCHAR,
    phone_secondary VARCHAR,
    email VARCHAR,
    gender VARCHAR CHECK (gender IN ('male', 'female')),
    date_of_birth DATE,
    age INTEGER,
    parent_name VARCHAR,
    parent_phone VARCHAR,
    parent_phone_secondary VARCHAR,
    parent_email VARCHAR,
    parent_relationship VARCHAR,
    country_id UUID REFERENCES public.countries(id) ON DELETE SET NULL,
    city VARCHAR,
    address TEXT,
    timezone VARCHAR,
    pricing_plan_id UUID REFERENCES public.pricing_plans(id) ON DELETE SET NULL,
    custom_monthly_price NUMERIC,
    discount_percentage NUMERIC DEFAULT 0,
    discount_reason TEXT,
    excuse_balance INTEGER DEFAULT 5 CHECK (excuse_balance >= 0),
    max_excuses_per_month INTEGER DEFAULT 5,
    warnings_count INTEGER DEFAULT 0 CHECK (warnings_count >= 0),
    current_level VARCHAR,
    memorization_progress TEXT,
    current_surah VARCHAR,
    current_page INTEGER,
    total_pages_memorized INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended', 'graduated', 'on_hold', 'transferred')),
    enrollment_date DATE DEFAULT CURRENT_DATE,
    graduation_date DATE,
    last_session_date DATE,
    next_session_date DATE,
    overall_performance NUMERIC CHECK (overall_performance >= 0 AND overall_performance <= 5),
    attendance_rate NUMERIC DEFAULT 100,
    preferred_teacher_id UUID REFERENCES public.teachers(id) ON DELETE SET NULL,
    preferred_session_time TIME,
    special_needs TEXT,
    medical_conditions TEXT,
    emergency_contact VARCHAR,
    emergency_phone VARCHAR,
    notes TEXT,
    profile_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. scheduled_sessions (depends on students, teachers)
CREATE TABLE public.scheduled_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    teacher_id UUID NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    session_time TIME NOT NULL,
    session_duration INTEGER DEFAULT 60 CHECK (session_duration > 0),
    start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    end_date DATE,
    session_type VARCHAR DEFAULT 'regular' CHECK (session_type IN ('regular', 'intensive', 'review', 'exam')),
    is_active BOOLEAN DEFAULT true,
    is_recurring BOOLEAN DEFAULT true,
    room_number VARCHAR,
    meeting_link TEXT,
    is_online BOOLEAN DEFAULT false,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. sessions (depends on scheduled_sessions, students, teachers, self-ref)
CREATE TABLE public.sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scheduled_session_id UUID REFERENCES public.scheduled_sessions(id) ON DELETE SET NULL,
    student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    teacher_id UUID NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
    session_date DATE NOT NULL,
    session_time TIME NOT NULL,
    actual_start_time TIMESTAMPTZ,
    actual_end_time TIMESTAMPTZ,
    session_duration INTEGER DEFAULT 60,
    actual_duration INTEGER CHECK (actual_duration IS NULL OR actual_duration > 0),
    status VARCHAR DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'student_excused', 'teacher_cancelled', 'student_absent', 'teacher_absent', 'rescheduled', 'cancelled')),
    is_makeup BOOLEAN DEFAULT false,
    makeup_for_session_id UUID REFERENCES public.sessions(id) ON DELETE SET NULL,
    session_type VARCHAR DEFAULT 'regular' CHECK (session_type IN ('regular', 'makeup', 'trial', 'assessment', 'review')),
    student_progress TEXT,
    pages_memorized INTEGER DEFAULT 0,
    pages_reviewed INTEGER DEFAULT 0,
    mistakes_count INTEGER DEFAULT 0,
    surah_name VARCHAR,
    from_page INTEGER,
    to_page INTEGER,
    from_ayah INTEGER,
    to_ayah INTEGER,
    teacher_notes TEXT,
    student_notes TEXT,
    admin_notes TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    performance_level VARCHAR CHECK (performance_level IN ('excellent', 'good', 'average', 'needs_improvement', 'poor')),
    student_attendance VARCHAR CHECK (student_attendance IN ('present', 'late', 'absent', 'excused')),
    teacher_attendance VARCHAR CHECK (teacher_attendance IN ('present', 'late', 'absent')),
    student_late_minutes INTEGER DEFAULT 0,
    teacher_late_minutes INTEGER DEFAULT 0,
    is_online BOOLEAN DEFAULT false,
    meeting_link TEXT,
    recording_link TEXT,
    attachments JSONB,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    rescheduled_to_date DATE,
    rescheduled_to_time TIME,
    completed_by VARCHAR,
    cancelled_by VARCHAR,
    cancellation_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. attendance_log (depends on sessions, students, teachers)
CREATE TABLE public.attendance_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    teacher_id UUID NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
    attendance_type VARCHAR NOT NULL CHECK (attendance_type IN ('present', 'excused', 'absent', 'late', 'left_early')),
    check_in_time TIMESTAMPTZ,
    check_out_time TIMESTAMPTZ,
    late_minutes INTEGER DEFAULT 0,
    early_leave_minutes INTEGER DEFAULT 0,
    logged_by VARCHAR CHECK (logged_by IN ('admin', 'teacher', 'student', 'system', 'auto')),
    logged_by_user_id UUID,
    reason TEXT,
    excuse_document_url TEXT,
    is_excuse_approved BOOLEAN,
    approved_by VARCHAR,
    approved_at TIMESTAMPTZ,
    notes TEXT,
    ip_address VARCHAR,
    device_info TEXT,
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. invoices (depends on students)
CREATE TABLE public.invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_number VARCHAR NOT NULL UNIQUE,
    student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    month INTEGER NOT NULL CHECK (month >= 1 AND month <= 12),
    year INTEGER NOT NULL CHECK (year >= 2024),
    billing_period_start DATE NOT NULL,
    billing_period_end DATE NOT NULL,
    base_amount NUMERIC NOT NULL CHECK (base_amount >= 0),
    discount_amount NUMERIC DEFAULT 0 CHECK (discount_amount >= 0),
    discount_percentage NUMERIC DEFAULT 0,
    discount_reason TEXT,
    additional_charges NUMERIC DEFAULT 0 CHECK (additional_charges >= 0),
    additional_charges_description TEXT,
    tax_amount NUMERIC DEFAULT 0 CHECK (tax_amount >= 0),
    tax_percentage NUMERIC DEFAULT 0,
    subtotal NUMERIC NOT NULL,
    total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
    amount_paid NUMERIC DEFAULT 0 CHECK (amount_paid >= 0),
    amount_due NUMERIC NOT NULL,
    currency_code VARCHAR NOT NULL,
    currency_symbol VARCHAR NOT NULL,
    expected_sessions INTEGER NOT NULL CHECK (expected_sessions >= 0),
    completed_sessions INTEGER DEFAULT 0 CHECK (completed_sessions >= 0),
    cancelled_by_teacher INTEGER DEFAULT 0 CHECK (cancelled_by_teacher >= 0),
    cancelled_by_student INTEGER DEFAULT 0 CHECK (cancelled_by_student >= 0),
    absent_sessions INTEGER DEFAULT 0 CHECK (absent_sessions >= 0),
    makeup_sessions INTEGER DEFAULT 0 CHECK (makeup_sessions >= 0),
    status VARCHAR DEFAULT 'draft' CHECK (status IN ('draft', 'pending', 'sent', 'paid', 'partial', 'overdue', 'cancelled', 'refunded', 'disputed')),
    issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    sent_date DATE,
    paid_date DATE,
    last_payment_date DATE,
    payment_terms TEXT,
    payment_instructions TEXT,
    notes TEXT,
    internal_notes TEXT,
    terms_and_conditions TEXT,
    created_by VARCHAR,
    approved_by VARCHAR,
    approved_at TIMESTAMPTZ,
    pdf_url TEXT,
    attachments JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. payments (depends on invoices, students)
CREATE TABLE public.payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_number VARCHAR NOT NULL UNIQUE,
    invoice_id UUID NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    currency_code VARCHAR NOT NULL,
    currency_symbol VARCHAR NOT NULL,
    payment_method VARCHAR NOT NULL CHECK (payment_method IN ('cash', 'bank_transfer', 'credit_card', 'debit_card', 'paypal', 'stripe', 'vodafone_cash', 'orange_cash', 'etisalat_cash', 'instapay', 'fawry', 'check', 'other')),
    transaction_reference VARCHAR,
    transaction_id VARCHAR,
    payment_gateway VARCHAR,
    gateway_response JSONB,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_time TIME DEFAULT CURRENT_TIME,
    transaction_date TIMESTAMPTZ DEFAULT NOW(),
    status VARCHAR DEFAULT 'completed' CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled', 'refunded', 'disputed')),
    bank_name VARCHAR,
    account_number VARCHAR,
    account_holder_name VARCHAR,
    check_number VARCHAR,
    check_date DATE,
    check_bank VARCHAR,
    received_by VARCHAR,
    received_by_user_id UUID,
    processed_by VARCHAR,
    verified_by VARCHAR,
    verified_at TIMESTAMPTZ,
    refund_amount NUMERIC DEFAULT 0,
    refund_date DATE,
    refund_reason TEXT,
    refunded_by VARCHAR,
    notes TEXT,
    receipt_url TEXT,
    attachments JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. warnings (depends on students)
CREATE TABLE public.warnings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    warning_number VARCHAR NOT NULL UNIQUE,
    student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    warning_type VARCHAR NOT NULL CHECK (warning_type IN ('excessive_excuses', 'excessive_absences', 'payment_overdue', 'behavior', 'performance', 'late_arrival', 'violation', 'other')),
    severity VARCHAR DEFAULT 'medium' CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    title VARCHAR NOT NULL,
    reason TEXT NOT NULL,
    description TEXT,
    action_taken TEXT,
    recommended_action TEXT,
    status VARCHAR DEFAULT 'active' CHECK (status IN ('active', 'acknowledged', 'resolved', 'escalated', 'dismissed')),
    issued_by VARCHAR,
    issued_by_user_id UUID,
    issued_at TIMESTAMPTZ DEFAULT NOW(),
    acknowledged_by VARCHAR,
    acknowledged_at TIMESTAMPTZ,
    resolved_by VARCHAR,
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT,
    follow_up_required BOOLEAN DEFAULT false,
    follow_up_date DATE,
    follow_up_notes TEXT,
    parent_notified BOOLEAN DEFAULT false,
    parent_notified_at TIMESTAMPTZ,
    notification_method VARCHAR,
    notes TEXT,
    attachments JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. holidays (depends on countries)
CREATE TABLE public.holidays (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL,
    name_ar VARCHAR,
    name_en VARCHAR,
    description TEXT,
    holiday_date DATE NOT NULL,
    end_date DATE,
    country_id UUID REFERENCES public.countries(id) ON DELETE CASCADE,
    holiday_type VARCHAR CHECK (holiday_type IN ('national', 'religious', 'school', 'custom')),
    is_recurring BOOLEAN DEFAULT false,
    recurrence_pattern VARCHAR,
    is_working_day BOOLEAN DEFAULT false,
    affects_billing BOOLEAN DEFAULT true,
    color VARCHAR,
    notes TEXT,
    created_by VARCHAR,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. audit_log (no dependencies)
CREATE TABLE public.audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    table_name VARCHAR NOT NULL,
    record_id UUID NOT NULL,
    action VARCHAR NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE', 'SELECT')),
    old_data JSONB,
    new_data JSONB,
    changed_fields JSONB,
    changed_by VARCHAR,
    changed_by_user_id UUID,
    user_role VARCHAR,
    ip_address VARCHAR,
    user_agent TEXT,
    session_id VARCHAR,
    changed_at TIMESTAMPTZ DEFAULT NOW(),
    reason TEXT,
    notes TEXT
);

-- 13. system_settings (no dependencies)
CREATE TABLE public.system_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    setting_key VARCHAR NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    setting_type VARCHAR NOT NULL CHECK (setting_type IN ('string', 'number', 'boolean', 'json', 'date', 'time')),
    category VARCHAR,
    description TEXT,
    is_public BOOLEAN DEFAULT false,
    is_editable BOOLEAN DEFAULT true,
    default_value TEXT,
    validation_rules JSONB,
    display_order INTEGER DEFAULT 0,
    updated_by VARCHAR,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. notifications (no dependencies)
CREATE TABLE public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recipient_type VARCHAR NOT NULL CHECK (recipient_type IN ('student', 'teacher', 'admin', 'parent', 'all')),
    recipient_id UUID,
    recipient_email VARCHAR,
    recipient_phone VARCHAR,
    notification_type VARCHAR NOT NULL CHECK (notification_type IN ('session_reminder', 'session_cancelled', 'session_rescheduled', 'payment_due', 'payment_received', 'payment_overdue', 'warning_issued', 'excuse_limit_reached', 'invoice_generated', 'general_announcement', 'system_alert', 'other')),
    priority VARCHAR DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    title VARCHAR NOT NULL,
    message TEXT NOT NULL,
    message_ar TEXT,
    message_en TEXT,
    send_email BOOLEAN DEFAULT false,
    send_sms BOOLEAN DEFAULT false,
    send_push BOOLEAN DEFAULT false,
    send_whatsapp BOOLEAN DEFAULT false,
    status VARCHAR DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'delivered', 'failed', 'read')),
    scheduled_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    email_status VARCHAR,
    sms_status VARCHAR,
    push_status VARCHAR,
    whatsapp_status VARCHAR,
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 3,
    related_entity_type VARCHAR,
    related_entity_id UUID,
    metadata JSONB,
    attachments JSONB,
    created_by VARCHAR,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. student_progress (depends on students, sessions, teachers)
CREATE TABLE public.student_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    session_id UUID REFERENCES public.sessions(id) ON DELETE SET NULL,
    teacher_id UUID REFERENCES public.teachers(id) ON DELETE SET NULL,
    progress_date DATE NOT NULL DEFAULT CURRENT_DATE,
    progress_type VARCHAR CHECK (progress_type IN ('memorization', 'review', 'recitation', 'tajweed', 'assessment')),
    surah_number INTEGER CHECK (surah_number >= 1 AND surah_number <= 114),
    surah_name VARCHAR,
    from_ayah INTEGER,
    to_ayah INTEGER,
    from_page INTEGER,
    to_page INTEGER,
    juz_number INTEGER CHECK (juz_number >= 1 AND juz_number <= 30),
    mastery_level VARCHAR CHECK (mastery_level IN ('excellent', 'good', 'average', 'needs_work', 'poor')),
    accuracy_percentage NUMERIC CHECK (accuracy_percentage >= 0 AND accuracy_percentage <= 100),
    fluency_rating INTEGER CHECK (fluency_rating >= 1 AND fluency_rating <= 5),
    tajweed_rating INTEGER CHECK (tajweed_rating >= 1 AND tajweed_rating <= 5),
    mistakes_count INTEGER DEFAULT 0,
    mistake_types JSONB,
    teacher_notes TEXT,
    strengths TEXT,
    areas_for_improvement TEXT,
    homework_assigned TEXT,
    is_completed BOOLEAN DEFAULT false,
    is_verified BOOLEAN DEFAULT false,
    verified_by UUID REFERENCES public.teachers(id) ON DELETE SET NULL,
    verified_at TIMESTAMPTZ,
    duration_minutes INTEGER,
    recording_url TEXT,
    attachments JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. teacher_availability (depends on teachers)
CREATE TABLE public.teacher_availability (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id UUID NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_available BOOLEAN DEFAULT true,
    availability_type VARCHAR CHECK (availability_type IN ('regular', 'temporary', 'exception')),
    exception_date DATE,
    exception_start_date DATE,
    exception_end_date DATE,
    max_students_per_slot INTEGER DEFAULT 1,
    slot_duration INTEGER DEFAULT 60,
    break_duration INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 17. student_documents (depends on students)
CREATE TABLE public.student_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    document_type VARCHAR NOT NULL CHECK (document_type IN ('id_card', 'birth_certificate', 'photo', 'medical_report', 'enrollment_form', 'parent_id', 'contract', 'certificate', 'report_card', 'other')),
    document_name VARCHAR NOT NULL,
    file_url TEXT NOT NULL,
    file_type VARCHAR,
    file_size INTEGER,
    description TEXT,
    issue_date DATE,
    expiry_date DATE,
    is_verified BOOLEAN DEFAULT false,
    verified_by VARCHAR,
    verified_at TIMESTAMPTZ,
    uploaded_by VARCHAR,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 18. teacher_documents (depends on teachers)
CREATE TABLE public.teacher_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id UUID NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
    document_type VARCHAR NOT NULL CHECK (document_type IN ('id_card', 'cv', 'certificate', 'degree', 'ijazah', 'contract', 'background_check', 'photo', 'other')),
    document_name VARCHAR NOT NULL,
    file_url TEXT NOT NULL,
    file_type VARCHAR,
    file_size INTEGER,
    description TEXT,
    issue_date DATE,
    expiry_date DATE,
    is_verified BOOLEAN DEFAULT false,
    verified_by VARCHAR,
    verified_at TIMESTAMPTZ,
    uploaded_by VARCHAR,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 19. expense_categories (self-referencing)
CREATE TABLE public.expense_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL UNIQUE,
    name_ar VARCHAR,
    name_en VARCHAR,
    description TEXT,
    parent_category_id UUID REFERENCES public.expense_categories(id) ON DELETE SET NULL,
    category_type VARCHAR CHECK (category_type IN ('operational', 'administrative', 'marketing', 'salaries', 'utilities', 'other')),
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 20. expenses (depends on expense_categories)
CREATE TABLE public.expenses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    expense_number VARCHAR NOT NULL UNIQUE,
    category_id UUID REFERENCES public.expense_categories(id) ON DELETE SET NULL,
    title VARCHAR NOT NULL,
    description TEXT,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    currency_code VARCHAR NOT NULL,
    currency_symbol VARCHAR,
    expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_method VARCHAR CHECK (payment_method IN ('cash', 'bank_transfer', 'credit_card', 'check', 'other')),
    vendor_name VARCHAR,
    vendor_contact TEXT,
    status VARCHAR DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'paid', 'rejected', 'cancelled')),
    requested_by VARCHAR,
    approved_by VARCHAR,
    approved_at TIMESTAMPTZ,
    paid_by VARCHAR,
    paid_at TIMESTAMPTZ,
    invoice_number VARCHAR,
    receipt_url TEXT,
    is_recurring BOOLEAN DEFAULT false,
    recurrence_pattern VARCHAR,
    notes TEXT,
    attachments JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 21. teacher_salaries (depends on teachers)
CREATE TABLE public.teacher_salaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    salary_number VARCHAR NOT NULL UNIQUE,
    teacher_id UUID NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
    month INTEGER NOT NULL CHECK (month >= 1 AND month <= 12),
    year INTEGER NOT NULL CHECK (year >= 2024),
    base_salary NUMERIC NOT NULL CHECK (base_salary >= 0),
    bonus_amount NUMERIC DEFAULT 0 CHECK (bonus_amount >= 0),
    bonus_reason TEXT,
    deduction_amount NUMERIC DEFAULT 0 CHECK (deduction_amount >= 0),
    deduction_reason TEXT,
    overtime_amount NUMERIC DEFAULT 0 CHECK (overtime_amount >= 0),
    total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
    currency_code VARCHAR NOT NULL,
    currency_symbol VARCHAR,
    total_sessions INTEGER DEFAULT 0,
    completed_sessions INTEGER DEFAULT 0,
    cancelled_sessions INTEGER DEFAULT 0,
    working_days INTEGER DEFAULT 0,
    absent_days INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'paid', 'rejected', 'on_hold')),
    payment_date DATE,
    approved_by VARCHAR,
    approved_at TIMESTAMPTZ,
    paid_by VARCHAR,
    paid_at TIMESTAMPTZ,
    payment_method VARCHAR,
    transaction_reference VARCHAR,
    notes TEXT,
    receipt_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 22. communication_log (no dependencies)
CREATE TABLE public.communication_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contact_type VARCHAR CHECK (contact_type IN ('student', 'parent', 'teacher', 'other')),
    contact_id UUID,
    contact_name VARCHAR,
    contact_phone VARCHAR,
    contact_email VARCHAR,
    communication_type VARCHAR CHECK (communication_type IN ('phone_call', 'email', 'sms', 'whatsapp', 'meeting', 'video_call', 'other')),
    direction VARCHAR CHECK (direction IN ('inbound', 'outbound')),
    subject VARCHAR,
    message TEXT,
    status VARCHAR DEFAULT 'completed' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'failed', 'cancelled')),
    scheduled_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    duration_minutes INTEGER,
    initiated_by VARCHAR,
    handled_by VARCHAR,
    follow_up_required BOOLEAN DEFAULT false,
    follow_up_date DATE,
    follow_up_notes TEXT,
    related_entity_type VARCHAR,
    related_entity_id UUID,
    notes TEXT,
    attachments JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 23. treasury_transactions (no dependencies)
CREATE TABLE public.treasury_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    transaction_number VARCHAR NOT NULL UNIQUE,
    currency_code VARCHAR NOT NULL,
    transaction_type VARCHAR NOT NULL CHECK (transaction_type IN ('deposit', 'withdrawal', 'salary_payment', 'payment_received')),
    amount NUMERIC NOT NULL,
    category VARCHAR,
    description TEXT,
    reference_type VARCHAR,
    reference_id UUID,
    transaction_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 24. treasury_transfers (no dependencies)
CREATE TABLE public.treasury_transfers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    transfer_number VARCHAR NOT NULL UNIQUE,
    from_currency VARCHAR NOT NULL,
    to_currency VARCHAR NOT NULL,
    from_amount NUMERIC NOT NULL,
    to_amount NUMERIC NOT NULL,
    exchange_rate NUMERIC NOT NULL,
    transfer_date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 25. system_keepalive (no dependencies)
CREATE TABLE public.system_keepalive (
    id INTEGER NOT NULL DEFAULT nextval('system_keepalive_id_seq'),
    last_ping_at TIMESTAMPTZ DEFAULT NOW(),
    ping_count INTEGER DEFAULT 0,
    notes TEXT DEFAULT 'Auto keepalive ping',
    CONSTRAINT system_keepalive_pkey PRIMARY KEY (id)
);
